### ISSUE TITLE
Include JSON data in body

### ISSUE THREAD

**Issue by APursch** [pietrantonio91/tablemanager#3]
Hi
Love the simplicity of your project.  How could I include JSON data array in the table body please?
Many thanks
Alan

**Comment by pietrantonio91** [comment]
Hi, thank you! Unfortunately it's not possible to do it now, but it can be an interesting improvement.

You can try something like this:
(sorry for bad formatting)

Empty table
`<table class="tablemanager"><thead></thead><tbody></tbody></table>`

External js includes
`<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
<script type="text/javascript" src="./tableManager.js"></script>`

Main JS:
`// get data from json
		let json = [
			{
				"Number": 1,
				"First Name": "Sara",
				"Last Name": "Jackson",
				"Date": "10-05-1988",
				"Points": 94
			},
			{
				"Number": 2,
				"First Name": "John",
				"Last Name": "Doe",
				"Date": "9-12-1967",
				"Points": 45
			}
		];
		
		if (json.length > 0) {			
			let head = Object.keys(json[0]);
			// populate thead
			$('.tablemanager').find('thead').append('<tr></tr>');
			$.each(head, function(key, col) {
				$('.tablemanager').find('thead tr').append('<th>'+col+'</th>');
			});

			// populate tbody
			$.each(json, function(key, row) {
				$('.tablemanager').find('tbody').append('<tr data-row="'+key+'"></tr>');
				$.each(row, function(i, col) {
					$('.tablemanager').find('tbody tr[data-row="'+key+'"]').append('<td>'+col+'</td>');
				});
			});

		}

		$('.tablemanager').tablemanager();`

**Comment by APursch** [comment]
Thank you for such a prompt reply Alessandro
Already the project has proved very useful to me; I'll explore your suggestions and let you know if I get it to work.
Stay healthy.
Kind regards
Alan

**Comment by APursch** [comment]
That worked first time out of the box, thank you so much!

**Comment by pietrantonio91** [comment]
Awesome, you're welcome!
